#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 03 16:45:57 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=
