name = "Starlight"
author = "my-daarlin"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44fd1fb15146a1b5e629ce1851cf72a31d1f93d5c3998921b58cebe7e115620c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
