#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Feb 13 15:38:41 PST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=5
shaderPack=
