name: Update Modrinth README

on:
  push:
    tags:
      - '*'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Update azalea.json
        run: python .github/scripts/update_azalea.py
        env:
          AZALEA_VERSION: ${{ github.ref_name }}
